/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bnkacc;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Nabeel Ahmed Siddiqui - https://github.com/nabeelsiddiquidev97
 */


class Account{
    private double balance;
    private int number;
    String name;
    char accType;
 
    Account(){
        
    }
    
    Account(double b,int no,String n,char at){
    balance=b;
    number=no;
    name=n;
    accType=at; 
    }
    
    Account(Account a){
    balance=a.balance;
    number=a.number;
    name=a.name;
    accType=a.accType; 
    }
    
    double getBalance(){
        return balance;
    }
    double getNumber(){
        return number;
    }   
    char getAccType(){
        return accType;
    } 
    void setBalance(double b){
        balance=b;
    } 
    
    
}

class SavingsAccount extends Account{
    double rate;
    double bal;
    
    SavingsAccount(Account sa){      
    bal=sa.getBalance();
    }
    
    
    SavingsAccount(){      
        }
    
    
    

    
    double getRate(){
        return rate;
    }
    
    double addInterest(){
        double ai=(bal*rate)/100;
        return ai;
    }
    
    
}
/**
 *
 * @author Nabeel Ahmed Siddiqi
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }
    Account acc1 = new Account(200.0, 100, "SSUET1", 's');
    Account ob=new Account(acc1);
    
  //  SavingsAccount ob1=new SavingsAccount();
    
    Account acc2 = new Account(300.0, 101, "SSUET2", 's');
    Account acc3 = new Account(400.0, 102, "SSUET3", 's');
    Account acc4 = new Account(500.0, 103, "SSUET4", 'c');
    Account acc5 = new Account(600.0, 104, "SSUET5", 'c');
    //Account ob=new Account(acc1);
    //double c= acc1.getBalance();
    SavingsAccount ob1=new SavingsAccount(acc1);
    SavingsAccount ob2=new SavingsAccount(acc2);
    SavingsAccount ob3=new SavingsAccount(acc3);
    SavingsAccount ob4=new SavingsAccount(acc4);
    SavingsAccount ob5=new SavingsAccount(acc5);
    double r=ob1.rate=ob2.rate=ob3.rate=ob4.rate=ob5.rate=10;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radbtnSavAcc = new javax.swing.JRadioButton();
        radbtnCurAcc = new javax.swing.JRadioButton();
        DispInfoBTN = new javax.swing.JButton();
        AddAccBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        PayCardBTN = new javax.swing.JButton();
        CI_BTN = new javax.swing.JButton();
        CardNoTF = new javax.swing.JTextField();
        CardNoLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(radbtnSavAcc);
        radbtnSavAcc.setText("Saving Account");
        radbtnSavAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbtnSavAccActionPerformed(evt);
            }
        });

        buttonGroup1.add(radbtnCurAcc);
        radbtnCurAcc.setText("Current Account");
        radbtnCurAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbtnCurAccActionPerformed(evt);
            }
        });

        DispInfoBTN.setText("Display info Sav or Cur");
        DispInfoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DispInfoBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DispInfoBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radbtnSavAcc)
                            .addComponent(radbtnCurAcc))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DispInfoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(radbtnSavAcc)
                .addGap(18, 18, 18)
                .addComponent(radbtnCurAcc)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        AddAccBTN.setText("Add All Account");
        AddAccBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAccBTNActionPerformed(evt);
            }
        });

        jLabel1.setText("Account List");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        PayCardBTN.setText("Pay By Card");

        CI_BTN.setText("Calculate Interest");
        CI_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CI_BTNActionPerformed(evt);
            }
        });

        CardNoLBL.setText("Card Number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(AddAccBTN)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PayCardBTN)
                    .addComponent(CardNoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CI_BTN)
                    .addComponent(CardNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(AddAccBTN)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CI_BTN)
                    .addComponent(PayCardBTN))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CardNoTF, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(CardNoLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CI_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CI_BTNActionPerformed
          double a1,a2,a3;
    
    a1=acc1.getBalance()+ob1.addInterest();
    a2=acc2.getBalance()+ob2.addInterest();
    a3=acc3.getBalance()+ob3.addInterest();
    JOptionPane.showMessageDialog(null,"\n***Saving Accounts*** \n" +
	"Account1: "+("Bal with Interest :"+a1+" No:"+acc1.getNumber()+" Name:"+acc1.name+" Acctype:"+acc1.accType)+ "\n" +
	"Account2: "+("Bal with Interest :"+a2+" No:"+acc2.getNumber()+" Name:"+acc2.name+" Acctype:"+acc2.accType)+"\n"+
        "Account3: "+("Bal with Interest :"+a3+" No:"+acc3.getNumber()+" Name:"+acc3.name+" Acctype:"+acc3.accType)  
        );

    }//GEN-LAST:event_CI_BTNActionPerformed

    private void AddAccBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAccBTNActionPerformed
     DefaultListModel model = new DefaultListModel();
       model.addElement("Bal:"+acc1.getBalance()+" No:"+acc1.getNumber()+" Name:"+acc1.name+" Acctype:"+acc1.accType);
       model.addElement("Bal:"+acc2.getBalance()+" No:"+acc2.getNumber()+" Name:"+acc2.name+" Acctype:"+acc2.accType);
       model.addElement("Bal:"+acc3.getBalance()+" No:"+acc3.getNumber()+" Name:"+acc3.name+" Acctype:"+acc3.accType);
       model.addElement("Bal:"+acc4.getBalance()+" No:"+acc4.getNumber()+" Name:"+acc4.name+" Acctype:"+acc4.accType);
       model.addElement("Bal:"+acc5.getBalance()+" No:"+acc5.getNumber()+" Name:"+acc5.name+" Acctype:"+acc5.accType);
       jList1.setModel(model);

    }//GEN-LAST:event_AddAccBTNActionPerformed

    private void DispInfoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DispInfoBTNActionPerformed
       if (radbtnSavAcc.isSelected()){
        JOptionPane.showMessageDialog(null,"\n***Saving Accounts*** \n" +
	"Account1: "+("Bal:"+acc1.getBalance()+" No:"+acc1.getNumber()+" Name:"+acc1.name+" Acctype:"+acc1.accType)+ "\n" +
	"Account2: "+("Bal:"+acc2.getBalance()+" No:"+acc2.getNumber()+" Name:"+acc2.name+" Acctype:"+acc2.accType)+"\n"+
        "Account3: "+("Bal:"+acc3.getBalance()+" No:"+acc3.getNumber()+" Name:"+acc3.name+" Acctype:"+acc3.accType)  
        );
            
                }
      else if(radbtnCurAcc.isSelected()){
         JOptionPane.showMessageDialog(null,"\n***Current Accounts*** \n" +
	"Account1: "+("Bal:"+acc4.getBalance()+" No:"+acc4.getNumber()+" Name:"+acc4.name+" Acctype:"+acc4.accType)+ "\n" +
	"Account2: "+("Bal:"+acc5.getBalance()+" No:"+acc5.getNumber()+" Name:"+acc5.name+" Acctype:"+acc5.accType)
        );
      }

    }//GEN-LAST:event_DispInfoBTNActionPerformed

    private void radbtnSavAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbtnSavAccActionPerformed
        CI_BTN.setEnabled(true);
            PayCardBTN.setEnabled(false);
            CardNoTF.setEnabled(false);
            CardNoLBL.setEnabled(false);
    }//GEN-LAST:event_radbtnSavAccActionPerformed

    private void radbtnCurAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbtnCurAccActionPerformed
    CI_BTN.setEnabled(false);
            PayCardBTN.setEnabled(true);
            CardNoTF.setEnabled(true);
            CardNoLBL.setEnabled(true);
    }//GEN-LAST:event_radbtnCurAccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAccBTN;
    private javax.swing.JButton CI_BTN;
    private javax.swing.JLabel CardNoLBL;
    private javax.swing.JTextField CardNoTF;
    private javax.swing.JButton DispInfoBTN;
    private javax.swing.JButton PayCardBTN;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radbtnCurAcc;
    private javax.swing.JRadioButton radbtnSavAcc;
    // End of variables declaration//GEN-END:variables
}
