/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EHT;

import javax.swing.JOptionPane;

/**
 *
 * @author Nabeel Ahmed Siddiqi - https://github.com/nabeelsiddiquidev97
 */
class InvalidRadiusException extends Exception{
    InvalidRadiusException(String msg){
        System.out.println(msg);
    }
}
class Circle{
    double r;
    
    Circle(double r) throws InvalidRadiusException{
    if(r==0)
    throw new InvalidRadiusException("Invalid Radius");
    this.r=r;
    }

    public double getRadius(){
    return r;
    }
    
}


public class ExcepHand extends javax.swing.JFrame {

    /**
     * Creates new form ExcepHand
     */
    public ExcepHand() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        DivZero_RadBtn = new javax.swing.JRadioButton();
        SqR_RadBtn = new javax.swing.JRadioButton();
        InvRad_RadBtn = new javax.swing.JRadioButton();
        Num_Lab = new javax.swing.JLabel();
        Den_Lab = new javax.swing.JLabel();
        Val_Lab = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        X_Lab = new javax.swing.JLabel();
        Y_Lab = new javax.swing.JLabel();
        Radius_Lab = new javax.swing.JLabel();
        Numer_TF = new javax.swing.JTextField();
        Denom_TF = new javax.swing.JTextField();
        SqRval_TF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        XCord_TF = new javax.swing.JTextField();
        YCord_TF = new javax.swing.JTextField();
        Rad_TF = new javax.swing.JTextField();
        SR_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(DivZero_RadBtn);
        DivZero_RadBtn.setText("DivideByZero");
        DivZero_RadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivZero_RadBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(SqR_RadBtn);
        SqR_RadBtn.setText("Square Root");
        SqR_RadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SqR_RadBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(InvRad_RadBtn);
        InvRad_RadBtn.setText("Invalid Radius");
        InvRad_RadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvRad_RadBtnActionPerformed(evt);
            }
        });

        Num_Lab.setText("Numerator");

        Den_Lab.setText("Denominator");

        Val_Lab.setText("Value");

        jLabel4.setText("Result");

        X_Lab.setText("X");

        Y_Lab.setText("Y");

        Radius_Lab.setText("Radius");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        SR_Btn.setText("Show Results");
        SR_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SR_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(DivZero_RadBtn)
                                .addGap(60, 60, 60))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SqR_RadBtn)
                                .addGap(64, 64, 64)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Val_Lab)
                                .addGap(35, 35, 35)
                                .addComponent(SqRval_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Num_Lab)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Numer_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(InvRad_RadBtn)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(X_Lab)
                            .addComponent(Y_Lab))
                        .addGap(4, 4, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(YCord_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(XCord_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Radius_Lab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Rad_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGap(15, 15, 15)
                .addComponent(Den_Lab)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Denom_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SR_Btn)
                .addGap(267, 267, 267))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Num_Lab)
                    .addComponent(DivZero_RadBtn)
                    .addComponent(Den_Lab)
                    .addComponent(Numer_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Denom_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SqR_RadBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Val_Lab)
                                .addComponent(SqRval_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InvRad_RadBtn)
                            .addComponent(X_Lab)
                            .addComponent(Radius_Lab)
                            .addComponent(XCord_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rad_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Y_Lab)
                            .addComponent(YCord_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(SR_Btn)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SR_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SR_BtnActionPerformed
                                      
        // TODO add your handling code here:
        String strDen=null;
        String strNum=null;
        String strVal=null;
        boolean isradBtnDBZSelected = DivZero_RadBtn.isSelected();
        boolean isradBtnIRSelected = InvRad_RadBtn.isSelected();
        boolean isradbtnSRSelected = SqR_RadBtn.isSelected();

        if(isradBtnDBZSelected){
        int a=Integer.parseInt(Numer_TF.getText());
        int b=Integer.parseInt(Denom_TF.getText());
        if(b==0){
         jTextArea1.setText("Math Error: Divided By Zero");
        }
        else{
        double c=(double)a/b;
        jTextArea1.setText(""+c);
        }
        }

        else if(isradBtnIRSelected){
         int a=Integer.parseInt(XCord_TF.getText());
         int b=Integer.parseInt(YCord_TF.getText());
         if(a==b){
         JOptionPane.showMessageDialog(this,"valRad-1");
         Rad_TF.setText("-1");
         }
        }

        else if(isradbtnSRSelected){
         int a=Integer.parseInt(SqRval_TF.getText());
         double c;
         if(a<=0){
         jTextArea1.setText("NaN");
         }   
         else{
         c=Math.sqrt(a);
         jTextArea1.setText("The Square Root of Value = "+c);}
        }

    }//GEN-LAST:event_SR_BtnActionPerformed

    private void DivZero_RadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivZero_RadBtnActionPerformed
        Num_Lab.setEnabled(true);
        Den_Lab.setEnabled(true);
        Radius_Lab.setEnabled(false);
        X_Lab.setEnabled(false);
        Y_Lab.setEnabled(false);
        Val_Lab.setEnabled(false);
        Rad_TF.setEnabled(false);
        Numer_TF.setEnabled(true);
        Denom_TF.setEnabled(true);
        XCord_TF.setEnabled(false);
        YCord_TF.setEnabled(false);
        SqRval_TF.setEnabled(false);
        
    }//GEN-LAST:event_DivZero_RadBtnActionPerformed

    private void SqR_RadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SqR_RadBtnActionPerformed
        Num_Lab.setEnabled(false);
        Den_Lab.setEnabled(false);
        Radius_Lab.setEnabled(false);
        X_Lab.setEnabled(false);
        Y_Lab.setEnabled(false);
        Val_Lab.setEnabled(true);
        Rad_TF.setEnabled(false);
        Numer_TF.setEnabled(false);
        Denom_TF.setEnabled(false);
        XCord_TF.setEnabled(false);
        YCord_TF.setEnabled(false);
        SqRval_TF.setEnabled(true);
    }//GEN-LAST:event_SqR_RadBtnActionPerformed

    private void InvRad_RadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvRad_RadBtnActionPerformed
        Num_Lab.setEnabled(false);
        Den_Lab.setEnabled(false);
        Radius_Lab.setEnabled(true);
        X_Lab.setEnabled(true);
        Y_Lab.setEnabled(true);
        Val_Lab.setEnabled(false);
        Rad_TF.setEnabled(true);
        Numer_TF.setEnabled(false);
        Denom_TF.setEnabled(false);
        XCord_TF.setEnabled(true);
        YCord_TF.setEnabled(true);
        SqRval_TF.setEnabled(false);
    }//GEN-LAST:event_InvRad_RadBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcepHand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcepHand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcepHand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcepHand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcepHand().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Den_Lab;
    private javax.swing.JTextField Denom_TF;
    private javax.swing.JRadioButton DivZero_RadBtn;
    private javax.swing.JRadioButton InvRad_RadBtn;
    private javax.swing.JLabel Num_Lab;
    private javax.swing.JTextField Numer_TF;
    private javax.swing.JTextField Rad_TF;
    private javax.swing.JLabel Radius_Lab;
    private javax.swing.JButton SR_Btn;
    private javax.swing.JRadioButton SqR_RadBtn;
    private javax.swing.JTextField SqRval_TF;
    private javax.swing.JLabel Val_Lab;
    private javax.swing.JTextField XCord_TF;
    private javax.swing.JLabel X_Lab;
    private javax.swing.JTextField YCord_TF;
    private javax.swing.JLabel Y_Lab;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
