/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Stable;
import javax.swing.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Nabeel Ahmed Siddiqi - https://github.com/nabeelsiddiquidev97
 */

abstract class Figure{
    double dim1;
    double dim2;

    Figure(double a, double b){
        dim1=a;
        dim2=b;
    }
    double getDim1(){
        return dim1;
    }
    
    double getDim2(){
        return dim2;
    }
    
    abstract double area();

}


class Triangle extends Figure{
    Triangle(double a, double b){
    super(a, b);
    }
    
    double area(){
    return (dim1 * dim2)/2.0;
    }

}


class Rectangle extends Figure{
    Rectangle(double a, double b){
    super(a,b);
    }
    
    double area(){
    return dim1 * dim2;
    }

}

class Circle extends Figure{
    Circle(double r){
    super(r,r);
    }

    double area(){
    return dim1 * dim2 * 3.14;
    }
    
}

public class ShapeTab extends javax.swing.JFrame {

    /**
     * Creates new form ShapeTab
     */
    DefaultTableModel model = new DefaultTableModel(new Object[]{"FigureName","Dimension 1","Dimension 2", "Dimension 3", "Dimension 4", "Area"},0  );
    Vector<String> rowOne = new Vector<String>();
    Vector<String> rowTwo = new Vector<String>();
    Vector<String> rowThree = new Vector<String>();
    String cBoBoxItem[]={"Rectangle","Circle","Triangle"};
    private DefaultComboBoxModel modelC=new DefaultComboBoxModel(cBoBoxItem);
    
    
    public ShapeTab() {
        initComponents();
        //modelC.addElement(cBoBoxItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Shape_Table = new javax.swing.JTable();
        AddDT_Btn = new javax.swing.JButton();
        ComboBox_1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Shape_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Figure Name", "Dimension 1", "Dimension 2", "Dimension 3", "Dimension 4", "Area"
            }
        ));
        jScrollPane1.setViewportView(Shape_Table);

        AddDT_Btn.setText("Add Data In Table");
        AddDT_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDT_BtnActionPerformed(evt);
            }
        });

        ComboBox_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBox_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(ComboBox_1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddDT_Btn)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(AddDT_Btn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(ComboBox_1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBox_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_1ActionPerformed
        // TODO add your handling code here:
      ComboBox_1.setModel(modelC);
      model.setRowCount(0); 
    }//GEN-LAST:event_ComboBox_1ActionPerformed

    
    private void AddDT_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDT_BtnActionPerformed
        // TODO add your handling code here:
         String cBoBoxItem1 = ComboBox_1.getSelectedItem().toString();
        double areaC1=0, areaC2 =0, areaC3=0;
        double areaR1=0, areaR2= 0, areaR3=0;
        double areaT1=0, areaT2= 0, areaT3=0;
        JOptionPane.showMessageDialog(null,"***Item Selected***\n"+"        "+cBoBoxItem1);
        int result1 = cBoBoxItem1.compareTo("Circle");
        int result2 = cBoBoxItem1.compareTo("Rectangle");
        int result3 = cBoBoxItem1.compareTo("Triangle");
        if(result1==0){
        //Create 3 objects of circle then call the method to get its dimension& in this way create three rows (i.e a vector having 3 entries) using vector & then store the vector in the DefaultTableModel& the set the table using :
        Circle c1=new Circle(10);
        Circle c2=new Circle(11);
        Circle c3=new Circle(12);
        model.addRow(new Object[]{"Circle 1",c1.getDim1(),null,null,null,c1.area()});
        model.addRow(new Object[]{"Circle 2",c2.getDim1(),null,null,null,c2.area()});
        model.addRow(new Object[]{"Circle 3",c3.getDim1(),null,null,null,c3.area()});
        Shape_Table.setModel(model);
        //Each row of the vector contains :
        //Object name (i.e  for example Circle 1) + dim1 + “ “ + “ “ + “ “ “ +area of rectangle
        }
        else if (result2==0){
        //Create 3 objects of rectangle then call the method to get their dimension & in this way create //three rows (i.e a vector having 3 entries) using vector & then store the vector in the //DefaultTableModel& the set the table using :
        Rectangle r1=new Rectangle(10,25);
        Rectangle r2=new Rectangle(11,6);
        Rectangle r3=new Rectangle(12,5);
        model.addRow(new Object[]{"Rectangle 1",r1.getDim1(),r1.getDim2(),null,null,r1.area()});
        model.addRow(new Object[]{"Rectangle 2",r2.getDim1(),r2.getDim2(),null,null,r2.area()});
        model.addRow(new Object[]{"Rectangle 3",r3.getDim1(),r3.getDim2(),null,null,r3.area()});
        Shape_Table.setModel(model);
        //Each row of the vector contains :
        //Object name(i.efor example Rectangle 1 )+ dim1 + dim2 + “ “ + “ “ “ +area of rectangle

        }
        else if(result3==0){
        //Create 3 objects of triangle then call the method to get their dimension & in this way create //three rows (i.e a vector having 3 entries) using vector & then store the vector in the //DefaultTableModel& the set the table using :    
        Triangle t1=new Triangle(10,25);
        Triangle t2=new Triangle(11,6);
        Triangle t3=new Triangle(12,5);
        model.addRow(new Object[]{"Triangle 1",t1.getDim1(),t1.getDim2(),null,null,t1.area()});
        model.addRow(new Object[]{"Triangle 2",t2.getDim1(),t2.getDim2(),null,null,t2.area()});
        model.addRow(new Object[]{"Triangle 3",t3.getDim1(),t3.getDim2(),null,null,t3.area()});
        Shape_Table.setModel(model);
        //Each row of the vector contains :
        //Object name (i.e for example Triangle 1 ) + dim1 + dim2 + “ “ + “ “ “ +area of rectangle
        }

    }//GEN-LAST:event_AddDT_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShapeTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShapeTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShapeTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShapeTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShapeTab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDT_Btn;
    private javax.swing.JComboBox<String> ComboBox_1;
    private javax.swing.JTable Shape_Table;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
